from pydantic import BaseModel, Field


class ArchitectureReview(BaseModel):
    summary: str
    detected_stack: list[str] = Field(default_factory=list)
    affected_areas: list[str] = Field(default_factory=list)
    likely_files: list[str] = Field(default_factory=list)
    recommended_approach: list[str] = Field(default_factory=list)
    risks: list[str] = Field(default_factory=list)
    security_notes: list[str] = Field(default_factory=list)
    testing_notes: list[str] = Field(default_factory=list)
    devops_notes: list[str] = Field(default_factory=list)
    open_questions: list[str] = Field(default_factory=list)
    confidence: str = "medium"
    confidence_score: float = 0.5
    source: str = "agent"

    @classmethod
    def fallback(
        cls,
        request: str,
        detected_stack: list[str] | None = None,
        likely_files: list[str] | None = None,
        risky_files: list[str] | None = None,
    ) -> "ArchitectureReview":
        detected_stack = detected_stack or []
        likely_files = likely_files or []
        risky_files = risky_files or []

        affected_areas = likely_files[:10] or ["unknown"]
        testing_notes = [
            "Run the detected test command before commit.",
            "If no test command is detected, document manual validation.",
        ]

        if detected_stack:
            testing_notes.append(
                f"Detected stack signals: {', '.join(detected_stack)}."
            )

        risks = [
            "Architecture review was generated by deterministic fallback.",
            "Human review is recommended before implementation.",
        ]

        if risky_files:
            risks.append(
                "Potentially risky files were detected and should be reviewed carefully."
            )

        return cls(
            summary=(
                "Deterministic architecture review fallback was used. "
                "Review the likely affected files, risks, and test notes before implementation."
            ),
            detected_stack=detected_stack,
            affected_areas=affected_areas,
            likely_files=likely_files,
            recommended_approach=[
                "Keep the change minimal and focused on the request.",
                "Prefer updating existing files over introducing new abstractions.",
                "Avoid unrelated refactors.",
            ],
            risks=risks,
            security_notes=[
                "Do not modify secrets, credentials, or environment files.",
                "Review any risky files before allowing patch application.",
            ],
            testing_notes=testing_notes,
            devops_notes=[
                "Check CI status before push or draft PR when available.",
            ],
            open_questions=[
                "Confirm whether the likely affected files fully cover the request."
            ],
            confidence="low",
            confidence_score=0.45,
            source="fallback",
        )
