from pydantic import BaseModel, Field


class ImplementationPlanStep(BaseModel):
    step_number: int
    title: str
    description: str
    target_files: list[str] = Field(default_factory=list)
    expected_changes: list[str] = Field(default_factory=list)
    test_impact: list[str] = Field(default_factory=list)
    risk_level: str = "low"
    acceptance_mapping: list[str] = Field(default_factory=list)
    rollback_notes: list[str] = Field(default_factory=list)


class ImplementationPlan(BaseModel):
    summary: str = ""
    steps: list[ImplementationPlanStep] = Field(default_factory=list)
    target_files: list[str] = Field(default_factory=list)
    test_strategy: list[str] = Field(default_factory=list)
    risks: list[str] = Field(default_factory=list)
    assumptions: list[str] = Field(default_factory=list)
    confidence_score: float = 0.5
    source: str = "agent"

    @classmethod
    def fallback(
        cls,
        request: str,
        likely_files: list[str] | None = None,
        testing_notes: list[str] | None = None,
        risk_notes: list[str] | None = None,
    ) -> "ImplementationPlan":
        likely_files = likely_files or []
        testing_notes = testing_notes or [
            "Run the detected test command before commit.",
        ]
        risk_notes = risk_notes or [
            "Implementation plan was generated by deterministic fallback.",
        ]
        target_files = likely_files[:10]
        steps = [
            ImplementationPlanStep(
                step_number=1,
                title="Review target context",
                description=(
                    "Review the request, architecture notes, likely files, and "
                    "current repository state before making changes."
                ),
                target_files=target_files,
                expected_changes=[
                    "Confirm the minimal set of files required for the requested change.",
                ],
                test_impact=[
                    "No direct test impact.",
                ],
                risk_level="low",
                acceptance_mapping=[
                    "Ensures implementation scope is understood before patch generation.",
                ],
                rollback_notes=[
                    "No code changes should be made in this step.",
                ],
            ),
            ImplementationPlanStep(
                step_number=2,
                title="Apply minimal implementation change",
                description=(
                    "Implement the requested change using the smallest focused patch possible."
                ),
                target_files=target_files,
                expected_changes=[
                    "Update existing files relevant to the request.",
                    "Avoid unrelated refactors.",
                ],
                test_impact=testing_notes,
                risk_level="medium" if risk_notes else "low",
                acceptance_mapping=[
                    "Requested behavior should be implemented or clearly documented.",
                ],
                rollback_notes=[
                    "Revert the generated patch if review or tests fail.",
                ],
            ),
            ImplementationPlanStep(
                step_number=3,
                title="Validate the change",
                description=(
                    "Run safe tests and review DeliveryOps tracking output before "
                    "commit, push, or PR."
                ),
                target_files=[],
                expected_changes=[
                    "No additional code changes unless validation identifies a failure.",
                ],
                test_impact=testing_notes,
                risk_level="low",
                acceptance_mapping=[
                    "Tests pass or failures are analyzed and documented.",
                ],
                rollback_notes=[
                    "If validation fails, do not proceed to commit/push without review.",
                ],
            ),
        ]
        return cls(
            summary=(
                "Deterministic implementation plan fallback was used. "
                "Review target files, tests, and risks before generating a patch."
            ),
            steps=steps,
            target_files=target_files,
            test_strategy=testing_notes,
            risks=risk_notes,
            assumptions=[
                "Fallback planning was used because the planner agent was unavailable or returned unusable output.",
            ],
            confidence_score=0.45,
            source="fallback",
        )
