from pydantic import BaseModel, Field


class IssueSpec(BaseModel):
    title: str
    body: str
    labels: list[str] = Field(default_factory=list)
    acceptance_criteria: list[str] = Field(default_factory=list)
    definition_of_done: list[str] = Field(default_factory=list)
    technical_notes: list[str] = Field(default_factory=list)
    risk_notes: list[str] = Field(default_factory=list)

    @classmethod
    def from_feature_request(
        cls,
        request_title: str,
        request_summary: str,
    ) -> "IssueSpec":
        title = request_title.strip() or "DeliveryOps request"
        summary = request_summary.strip()

        body = "\n".join(
            [
                "## Problem",
                "",
                summary or "No problem statement provided.",
                "",
                "## Goal",
                "",
                summary or "No goal provided.",
                "",
                "## Scope",
                "",
                "- Implement the requested change with minimal, reviewable updates.",
                "",
                "## Out of Scope",
                "",
                "- Unrelated refactors",
                "- Production deployment",
                "- Secret or environment file changes",
                "",
                "## Acceptance Criteria",
                "",
                "- The requested behavior is implemented or clearly documented.",
                "- Relevant tests are added or existing tests pass.",
                "- DeliveryOps tracking files are updated during the workflow.",
                "",
                "## Definition of Done",
                "",
                "- Patch is reviewed and approved before application.",
                "- Tests pass or failures are clearly analyzed.",
                "- Commit, push, and draft PR actions require approval.",
                "",
                "## Technical Notes",
                "",
                "- Generated by DeliveryOps Product Owner fallback.",
                "",
                "## Risk Notes",
                "",
                "- Review generated content before implementation.",
            ]
        )

        return cls(
            title=title,
            body=body,
            labels=["deliveryops"],
            acceptance_criteria=[
                "The requested behavior is implemented or clearly documented.",
                "Relevant tests are added or existing tests pass.",
            ],
            definition_of_done=[
                "Patch is reviewed and approved before application.",
                "Tests pass or failures are clearly analyzed.",
            ],
            technical_notes=["Generated by DeliveryOps Product Owner fallback."],
            risk_notes=["Review generated content before implementation."],
        )
