from pathlib import Path

from app.schemas.delivery_state import DeliveryState
from app.tools.diff_tools import build_unified_diff, write_generated_patch


def can_generate_readme_patch(state: DeliveryState) -> bool:
    request = state.original_request.lower()

    return any(
        keyword in request
        for keyword in ["readme", "documentation", "docs", "document"]
    )


import subprocess
from pathlib import Path

from app.schemas.delivery_state import DeliveryState
from app.tools.diff_tools import write_generated_patch


def can_generate_readme_patch(state: DeliveryState) -> bool:
    request = state.original_request.lower()

    return any(
        keyword in request
        for keyword in ["readme", "documentation", "docs", "document"]
    )


def build_readme_patch(repo_path: Path, state: DeliveryState) -> str:
    readme_path = repo_path / "README.md"

    if not readme_path.exists():
        raise FileNotFoundError("README.md not found. Cannot generate README patch.")

    before = readme_path.read_text(encoding="utf-8")

    section = """

## DeliveryOps Generated Update

This section was generated by DeliveryOps as part of an approved patch workflow.
"""

    if "## DeliveryOps Generated Update" in before:
        return ""

    try:
        readme_path.write_text(before.rstrip() + section + "\n", encoding="utf-8")

        result = subprocess.run(
            ["git", "diff", "--", "README.md"],
            cwd=repo_path,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )

        if result.returncode != 0:
            raise RuntimeError(result.stderr)

        return result.stdout
    finally:
        readme_path.write_text(before, encoding="utf-8")


def generate_patch(repo_path: Path, state: DeliveryState) -> Path | None:
    if can_generate_readme_patch(state):
        patch_content = build_readme_patch(repo_path, state)

        if not patch_content.strip():
            return None

        return write_generated_patch(repo_path, patch_content)

    return None


def generate_patch(repo_path: Path, state: DeliveryState) -> Path | None:
    if can_generate_readme_patch(state):
        patch_content = build_readme_patch(repo_path, state)
        return write_generated_patch(repo_path, patch_content)

    return None